# Use the official Node.js image as the base image
FROM node:14

# Create and change to the app directory
WORKDIR /src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 5983

# Start the app
CMD ["npm", "start"]
