# Need static ip to always access to that cluster ip
# Need nodeport to access to that too 

apiVersion: v1
kind: Service
metadata:
  name: main-server-nodeport-service
  labels:
    app: main-server
spec:
  selector:
    app: main-server
  ports:
    - protocol: TCP
      port: 5000 # export port 
      targetPort: 5000 #app port
      nodePort: 31230 # export port 
  type: NodePort
  clusterIP: 10.152.183.100