apiVersion: v1
kind: Service
metadata:
  name: main-server-service
spec:
  selector:
    app: main-server
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  clusterIP: 10.152.183.100
  type: ClusterIP
