apiVersion: v2
name: ondemandchart
description: A Helm chart for Kubernetes on demand deployment, creates main-server, orchestrator and microservice
type: application
version: 0.1.0
appVersion: "1.16.0"
