#global vars 
# helm install <release-name> <chart-name> --set image.name=localhost:5000 # use local 
registry: inaki99

namespaceprod: ondemand
imagearchitecture: arm64

#app vars
app:
  name: app-container # main
  image: app
  tag: latest
  port: 5000
  staticIP: 10.152.183.100
  nodePort: 31230

#microservices vars
microservice:
  name: microservice-container
  image: microservice
  tag: latest
  port: 5983

#orchestrator vars
orchestrator:
  name: orchestrator-container
  image: orchestrator
  tag: latest
  port: 5045
  staticIP: 10.152.183.101
  nodePort: 31231

  # curl 


# DESDE DENTRO DE UN POD curl 10.1.254.99:5045 O orchestrator-container-nodeport-service:5045 (clusterDNS communication)
# DESDE AFUERA POR EL NODE PORT 
# DESDE INGRESS IGUAL ANOTAR ETC HOSTS NODE PORT Y ROUTE