apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.orchestrator.name }}
  namespace: {{ .Values.namespaceprod }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.orchestrator.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.orchestrator.name }}
        identifier: k8sondemand
    spec:
      containers:
      - name: {{ .Values.orchestrator.name }}
        #image: inaki99/microservice-arm64:latest
        image: {{ .Values.registry }}/{{ .Values.orchestrator.image }}-{{ .Values.imagearchitecture }}:{{ .Values.orchestrator.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.orchestrator.port }}
