apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.orchestrator.name }}-nodeport-service
  namespace: {{ .Values.namespaceprod }}
  labels:
    app: {{ .Values.orchestrator.name }}
    identifier: k8sondemand
spec:
  selector:
    app: {{ .Values.orchestrator.name }} # select pods with this labels -> deployment create pods with this template.app
  ports:
  - protocol: TCP
    port: {{ .Values.orchestrator.port }} # export port
    targetPort: {{ .Values.orchestrator.port }} #app port
    nodePort: {{ .Values.orchestrator.nodePort }} # export port
  clusterIP: {{ .Values.orchestrator.staticIP }}
  type: NodePort
