apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.orchestrator.name }}-nodeport-service
  labels:
    app: orchestrator
spec:
  selector:
    app: orchestrator
  ports:
  - protocol: TCP
    port: {{ .Values.orchestrator.port }} # export port
    targetPort: {{ .Values.orchestrator.port }} #app port
    nodePort: {{ .Values.orchestrator.nodePort }} # export port
  clusterIP: {{ .Values.orchestrator.staticIP }}
  type: NodePort
