apiVersion: v1
kind: Service
metadata:
  name: orchestrator-nodeport-service
  labels:
    app: orchestrator
spec:
  selector:
    app: orchestrator
  ports:
  - protocol: TCP
    port: 5045 # export port
    targetPort: 5045 #app port
    nodePort: 31231 # export port 
  clusterIP: 10.152.183.101
  type: NodePort
