apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespaceprod }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template: # creates pods with this metadata template
    metadata:
      labels:
        app: {{ .Values.app.name }}
        identifier: k8sondemand
    spec:
      containers:
      - name: {{ .Values.app.name }}
        #image: inaki99/app-arm64:latest
        image: {{ .Values.registry }}/{{ .Values.app.image }}-{{ .Values.imagearchitecture }}:{{ .Values.app.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.app.port }}
        env:
          - name: ENV_VARIABLE
            value: "test_env_123"
        volumeMounts:
          - mountPath: /var/storage/host  # can be accessed in the container, local storage if needed or use a cloud provider to store
            # save on var/storage/host/logs.txt 
            # even if a redeploy happens, we have this storage 
            name: storage-host
      volumes: # Need to create the volume of the deploy 
        - name: storage-host
          hostPath:
            path: /var/logs/main-server
            type: DirectoryOrCreate
