apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-nodeport-service
  labels:
    app: {{ .Values.app.name }}
    identifier: k8sondemand
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.app.port }} # export port 
      targetPort: {{ .Values.app.port }} #app port
      nodePort: {{ .Values.app.nodePort }} # export port 
  type: NodePort
  clusterIP: {{ .Values.app.staticIP }}